language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage # Include coverage when running tests
after_success: # Upload coverage reports 
  - npm run coveralls