branches:
  only:
  - master
language: node_js
node_js:
- node
addons:
  sonarcloud:
    organization: lunotte
#    token:
#      secure: 104cccd30914117579b8b26ca9499e786cd9f3ed
cache:
  directories:
  - node_modules
script:
- npm test -- --coverage
- sonar-scanner
