language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "lunotte"
    token:
      secure: ${SONAR_TOKEN}
script:
  - npm test -- --coverage # Include coverage when running tests
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
after_success: # Upload coverage reports 
  - npm run coveralls