name: Publish in npm
on:
  pull_request:
    branches:
      - Livraison
    types: [closed]

jobs:
  job_publish:
    name: Publish if merged
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: echo merged and ready to publish
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Publish
        run: | 
              echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
              npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
